### ISSUE TITLE
能开放一下修改的ijkplayer 底层的源码吗

### ISSUE THREAD

**Issue by leigel** [wuhongsheng/wtplayer#1]
你好，我照网上的录像方式修改的之后硬解播放不能录像，你的正常，现在ijkplayer升级到ffmpeg4.0了，我想基于4.0的编译一版可以录像的，你能开放一下你修改的那部份源码吗

**Comment by wuhongsheng** [comment]
看下这个http://wuhongsheng.top/2020/08/22/ijkplayer-%E6%89%A9%E5%B1%95%E6%88%AA%E5%B1%8F%E5%92%8C%E5%BD%95%E5%83%8F%E6%96%B9%E6%B3%95/

**Comment by wuhongsheng** [comment]
> 你好，我照网上的录像方式修改的之后硬解播放不能录像，你的正常，现在ijkplayer升级到ffmpeg4.0了，我想基于4.0的编译一版可以录像的，你能开放一下你修改的那部份源码吗

看下这个http://wuhongsheng.top/2020/08/22/ijkplayer-%E6%89%A9%E5%B1%95%E6%88%AA%E5%B1%8F%E5%92%8C%E5%BD%95%E5%83%8F%E6%96%B9%E6%B3%95/
顺便问一句，你升级升级到ffmpeg4.0是为了优化什么问题吗
