### ISSUE TITLE
偶尔会崩溃

### ISSUE THREAD

**Issue by leigel** [wuhongsheng/wtplayer#2]
播放并录像之后，偶尔存在奔溃现象。

**Comment by wuhongsheng** [comment]
> 播放并录像之后，偶尔存在奔溃现象。

有崩溃日志吗

**Comment by wuhongsheng** [comment]
> 播放并录像之后，偶尔存在奔溃现象。

我这边也升级的ffmpeg 4.0了，录像崩溃的问题能提供日志或者复现路径吗

**Comment by leigel** [comment]
就是录像的时候偶尔会崩溃，这个是日志：
4-19 22:19:12.771  8641  8641 F DEBUG   : '
04-19 22:19:12.771  8641  8641 F DEBUG   : SYSVMTYPE: Art
04-19 22:19:12.771  8641  8641 F DEBUG   : APPVMTYPE: Art
04-19 22:19:12.771  8641  8641 F DEBUG   : pid: 30936, tid: 6803, name: Thread-29  >>> tv.danmaku.ijk.media.WTPlayer <<<
04-19 22:19:12.771  8641  8641 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-19 22:19:12.771  8641  8641 F DEBUG   : Abort message: 'Invalid address 0x7005d88540 passed to free: value not allocated'
04-19 22:19:12.771  8641  8641 F DEBUG   :     x0  0000000000000000  x1  0000000000001a93  x2  0000000000000006  x3  0000000000000008
04-19 22:19:12.771  8641  8641 F DEBUG   :     x4  8000000000808080  x5  8000000000808080  x6  8000000000808080  x7  0000000000000008
04-19 22:19:12.771  8641  8641 F DEBUG   :     x8  0000000000000083  x9  e2bd5ddefd765dc7  x10 0000000000000000  x11 fffffffc7ffffbdf
04-19 22:19:12.771  8641  8641 F DEBUG   :     x12 0000000000000001  x13 00000000607d9160  x14 00007cd9049a6f0c  x15 000018013915459a
04-19 22:19:12.771  8641  8641 F DEBUG   :     x16 00000070e60b02c0  x17 00000070e5feee34  x18 0000000000000001  x19 00000000000078d8
04-19 22:19:12.771  8641  8641 F DEBUG   :     x20 0000000000001a93  x21 0000007028d13808  x22 0000000000000000  x23 00000070e60bcc20
04-19 22:19:12.771  8641  8641 F DEBUG   :     x24 00000070e60bcc9c  x25 0000000000000000  x26 0000000000000000  x27 00000070137ff3a8
04-19 22:19:12.771  8641  8641 F DEBUG   :     x28 0000000000000000  x29 00000070137ff100
04-19 22:19:12.771  8641  8641 F DEBUG   :     sp  00000070137ff0c0  lr  00000070e5fe3960  pc  00000070e5fe3988
04-19 22:19:12.803  8641  8641 F DEBUG   : 
04-19 22:19:12.803  8641  8641 F DEBUG   : backtrace:
04-19 22:19:12.803  8641  8641 F DEBUG   :     #00 pc 0000000000022988  /system/lib64/libc.so (abort+116)
04-19 22:19:12.804  8641  8641 F DEBUG   :     #01 pc 00000000000a0db0  /system/lib64/libc.so (ifree+1204)
04-19 22:19:12.804  8641  8641 F DEBUG   :     #02 pc 00000000000a0edc  /system/lib64/libc.so (je_free+120)
04-19 22:19:12.804  8641  8641 F DEBUG   :     #03 pc 000000000028ee10  /data/app/tv.danmaku.ijk.media.WTPlayer-oo8CeKTGY4CNdSgXNw_8Ag==/lib/arm64/libijkffmpeg.so
04-19 22:19:12.882  8640  8640 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 8640 (dex2oat), pid 8640 (dex2oat)
04-19 22:19:17.306  8672  8672 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-19 22:19:17.306  8672  8672 F DEBUG   : Build fingerprint: 'HONOR/STF-AL10/HWSTF:9/HUAWEISTF-AL10/9.1.0.225C00:user/release-keys'
04-19 22:19:17.306  8672  8672 F DEBUG   : Revision: '0'
04-19 22:19:17.306  8672  8672 F DEBUG   : ABI: 'arm'
04-19 22:19:17.307  8672  8672 F DEBUG   : Happend: 'Mon Apr 19 22:19:17 2021


https://blog.csdn.net/qq_35624156/article/details/85159692

**Comment by leigel** [comment]
新版本ff4.0的依然奔溃
奔溃日志：
04-24 14:54:52.768 F/DEBUG   (30605): Build fingerprint: 'HONOR/STF-AL10/HWSTF:9/HUAWEISTF-AL10/9.1.0.225C00:user/release-keys'
04-24 14:54:52.768 F/DEBUG   (30605): Revision: '0'
04-24 14:54:52.768 F/DEBUG   (30605): ABI: 'arm64'
04-24 14:54:52.785 F/DEBUG   (30605): Happend: 'Sat Apr 24 14:54:52 2021
04-24 14:54:52.785 F/DEBUG   (30605): '
04-24 14:54:52.786 F/DEBUG   (30605): SYSVMTYPE: Art
04-24 14:54:52.786 F/DEBUG   (30605): APPVMTYPE: Art
04-24 14:54:52.786 F/DEBUG   (30605): pid: 18111, tid: 18353, name: ff_audio_dec  >>> tv.danmaku.ijk.media.WTPlayer.b <<<
04-24 14:54:52.786 F/DEBUG   (30605): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-24 14:54:52.786 F/DEBUG   (30605): Abort message: 'Invalid address 0x70444ad300 passed to free: value not allocated'
04-24 14:54:52.786 F/DEBUG   (30605):     x0  0000000000000000  x1  00000000000047b1  x2  0000000000000006  x3  0000000000000008
04-24 14:54:52.786 F/DEBUG   (30605):     x4  8000000000808080  x5  8000000000808080  x6  8000000000808080  x7  0000000000000008
04-24 14:54:52.786 F/DEBUG   (30605):     x8  0000000000000083  x9  e2bd5ddefd765dc7  x10 0000000000000000  x11 fffffffc7ffffbdf
04-24 14:54:52.786 F/DEBUG   (30605):     x12 0000000000000001  x13 000000006083c0bc  x14 0004f64a7ef1e000  x15 0000199594b54491
04-24 14:54:52.786 F/DEBUG   (30605):     x16 00000070e60b02c0  x17 00000070e5feee34  x18 0000000000000020  x19 00000000000046bf
04-24 14:54:52.786 F/DEBUG   (30605):     x20 00000000000047b1  x21 00000070478e3c08  x22 0000000000000000  x23 00000070e60bcc20
04-24 14:54:52.786 F/DEBUG   (30605):     x24 00000070e60bcc9c  x25 00000070464b0000  x26 0000007033301390  x27 000000703330138c
04-24 14:54:52.786 F/DEBUG   (30605):     x28 0000000000000001  x29 0000007033301220
04-24 14:54:52.786 F/DEBUG   (30605):     sp  00000070333011e0  lr  00000070e5fe3960  pc  00000070e5fe3988
04-24 14:54:52.824 F/DEBUG   (30605): 
04-24 14:54:52.824 F/DEBUG   (30605): backtrace:
04-24 14:54:52.824 F/DEBUG   (30605):     #00 pc 0000000000022988  /system/lib64/libc.so (abort+116)
04-24 14:54:52.824 F/DEBUG   (30605):     #01 pc 00000000000a0db0  /system/lib64/libc.so (ifree+1204)
04-24 14:54:52.824 F/DEBUG   (30605):     #02 pc 00000000000a0edc  /system/lib64/libc.so (je_free+120)
04-24 14:54:52.824 F/DEBUG   (30605):     #03 pc 00000000002b01ac  /data/app/tv.danmaku.ijk.media.WTPlayer.b-deo4uio2per3fFbuooX3GQ==/lib/arm64/libijkffmpeg.so
04-24 14:54:54.474 W/SocketListener(  576): sending broadcast to Pid = 1339, Uid = 1000 
04-24 14:54:54.539 I/chatty  ( 1339): uid=1000(system) DeviceStorageMo expire 4 lines
04-24 14:54:54.944 I/chatty  ( 1339): uid=1000(system) Binder:1339_18 expire 34 lines
04-24 14:54:55.002 I/chatty  ( 1339): uid=1000(system) android.ui expire 14 lines
04-24 14:54:56.479 W/SocketListener(  576): sending broadcast to Pid = 1339, Uid = 1000 
04-24 14:54:56.490 I/chatty  ( 1339): uid=1000(system) NetdConnector expire 20 lines
04-24 14:54:56.498 I/chatty  ( 1339): uid=1000(system) android.fg expire 10 lines
04-24 14:54:56.502 I/chatty  ( 1339): uid=1000(system) NetworkStats expire 25 lines
04-24 14:54:57.141 I/chatty  ( 1339): uid=1000 system_server expire 1 line
04-24 14:54:57.166 I/chatty  ( 1339): uid=1000(system) FileObserver expire 2 lines
04-24 14:54:57.310 I/chatty  ( 1339): uid=1000 system_server expire 1 line
04-24 14:54:57.424 I/chatty  ( 1339): uid=1000(system) Binder:1339_1F expire 5 lines
04-24 14:54:57.425 I/chatty  ( 1339): uid=1000 system_server expire 2 lines

**Comment by wuhongsheng** [comment]
> 新版本ff4.0的依然奔溃
> 奔溃日志：
> 04-24 14:54:52.768 F/DEBUG (30605): Build fingerprint: 'HONOR/STF-AL10/HWSTF:9/HUAWEISTF-AL10/9.1.0.225C00:user/release-keys'
> 04-24 14:54:52.768 F/DEBUG (30605): Revision: '0'
> 04-24 14:54:52.768 F/DEBUG (30605): ABI: 'arm64'
> 04-24 14:54:52.785 F/DEBUG (30605): Happend: 'Sat Apr 24 14:54:52 2021
> 04-24 14:54:52.785 F/DEBUG (30605): '
> 04-24 14:54:52.786 F/DEBUG (30605): SYSVMTYPE: Art
> 04-24 14:54:52.786 F/DEBUG (30605): APPVMTYPE: Art
> 04-24 14:54:52.786 F/DEBUG (30605): pid: 18111, tid: 18353, name: ff_audio_dec >>> tv.danmaku.ijk.media.WTPlayer.b <<<
> 04-24 14:54:52.786 F/DEBUG (30605): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
> 04-24 14:54:52.786 F/DEBUG (30605): Abort message: 'Invalid address 0x70444ad300 passed to free: value not allocated'
> 04-24 14:54:52.786 F/DEBUG (30605): x0 0000000000000000 x1 00000000000047b1 x2 0000000000000006 x3 0000000000000008
> 04-24 14:54:52.786 F/DEBUG (30605): x4 8000000000808080 x5 8000000000808080 x6 8000000000808080 x7 0000000000000008
> 04-24 14:54:52.786 F/DEBUG (30605): x8 0000000000000083 x9 e2bd5ddefd765dc7 x10 0000000000000000 x11 fffffffc7ffffbdf
> 04-24 14:54:52.786 F/DEBUG (30605): x12 0000000000000001 x13 000000006083c0bc x14 0004f64a7ef1e000 x15 0000199594b54491
> 04-24 14:54:52.786 F/DEBUG (30605): x16 00000070e60b02c0 x17 00000070e5feee34 x18 0000000000000020 x19 00000000000046bf
> 04-24 14:54:52.786 F/DEBUG (30605): x20 00000000000047b1 x21 00000070478e3c08 x22 0000000000000000 x23 00000070e60bcc20
> 04-24 14:54:52.786 F/DEBUG (30605): x24 00000070e60bcc9c x25 00000070464b0000 x26 0000007033301390 x27 000000703330138c
> 04-24 14:54:52.786 F/DEBUG (30605): x28 0000000000000001 x29 0000007033301220
> 04-24 14:54:52.786 F/DEBUG (30605): sp 00000070333011e0 lr 00000070e5fe3960 pc 00000070e5fe3988
> 04-24 14:54:52.824 F/DEBUG (30605):
> 04-24 14:54:52.824 F/DEBUG (30605): backtrace:
> 04-24 14:54:52.824 F/DEBUG (30605): #0 pc 0000000000022988 /system/lib64/libc.so (abort+116)
> 04-24 14:54:52.824 F/DEBUG (30605): #1 pc 00000000000a0db0 /system/lib64/libc.so (ifree+1204)
> 04-24 14:54:52.824 F/DEBUG (30605): #2 pc 00000000000a0edc /system/lib64/libc.so (je_free+120)
> 04-24 14:54:52.824 F/DEBUG (30605): #3 pc 00000000002b01ac /data/app/tv.danmaku.ijk.media.WTPlayer.b-deo4uio2per3fFbuooX3GQ==/lib/arm64/libijkffmpeg.so
> 04-24 14:54:54.474 W/SocketListener( 576): sending broadcast to Pid = 1339, Uid = 1000
> 04-24 14:54:54.539 I/chatty ( 1339): uid=1000(system) DeviceStorageMo expire 4 lines
> 04-24 14:54:54.944 I/chatty ( 1339): uid=1000(system) Binder:1339_18 expire 34 lines
> 04-24 14:54:55.002 I/chatty ( 1339): uid=1000(system) android.ui expire 14 lines
> 04-24 14:54:56.479 W/SocketListener( 576): sending broadcast to Pid = 1339, Uid = 1000
> 04-24 14:54:56.490 I/chatty ( 1339): uid=1000(system) NetdConnector expire 20 lines
> 04-24 14:54:56.498 I/chatty ( 1339): uid=1000(system) android.fg expire 10 lines
> 04-24 14:54:56.502 I/chatty ( 1339): uid=1000(system) NetworkStats expire 25 lines
> 04-24 14:54:57.141 I/chatty ( 1339): uid=1000 system_server expire 1 line
> 04-24 14:54:57.166 I/chatty ( 1339): uid=1000(system) FileObserver expire 2 lines
> 04-24 14:54:57.310 I/chatty ( 1339): uid=1000 system_server expire 1 line
> 04-24 14:54:57.424 I/chatty ( 1339): uid=1000(system) Binder:1339_1F expire 5 lines
> 04-24 14:54:57.425 I/chatty ( 1339): uid=1000 system_server expire 2 lines

我这边的几台设备暂时没有复现出你的崩溃，不好定位问题，看日志是ffmpeg的库报错了，应该和录像代码本身关系不大，你有没有用其他手机试试
